name: Editais Brasil (stub)

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Stub visível
        run: |
          echo "Workflow Brasil carregado com sucesso."
          echo "Depois troque este echo por: python monitor_editais_brasil.py"
