name: Editais Exterior (NL/DE/EU)

on:
  schedule:
    - cron: "15 11 * * *"   # 08:15 Fortaleza (UTC-3) ≈ 11:15 UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requirements
        run: pip install -r requirements.txt

      # ============ Smoke test: só quando for manual ============
      - name: Smoke-test email (manual only)
        if: github.event_name == 'workflow_dispatch'
        env:
          LANG_INT: en
          COUNTRY_INT: US
          DAYS_INT: 3
          MAX_PER_TERM_INT: 4
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASS: ${{ secrets.GMAIL_APP_PASS }}
          EMAIL_TO_EXTERIOR: ${{ secrets.EMAIL_TO_EXTERIOR }}
        run: python monitor_editais_exterior.py

      # ============ Execução normal (agendada) ============
      - name: Run monitor (scheduled)
        if: github.event_name != 'workflow_dispatch'
        env:
          LANG_INT: en
          COUNTRY_INT: US
          DAYS_INT: 14
          MAX_PER_TERM_INT: 8
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASS: ${{ secrets.GMAIL_APP_PASS }}
          EMAIL_TO_EXTERIOR: ${{ secrets.EMAIL_TO_EXTERIOR }}
        run: python monitor_editais_exterior.py
