name: Editais Internacionais (NL/DE/EU)

on:
  schedule:
    - cron: "20 11 * * *"   # 08:20 Fortaleza (UTC-3) ≈ 11:20 UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar monitor internacionais (NL/DE/EU)
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASS: ${{ secrets.GMAIL_APP_PASS }}
          EMAIL_TO_EXTERIOR: ${{ secrets.EMAIL_TO_EXTERIOR }}
          LANG: "en"
          COUNTRY: "US"
          DAYS: "14"
          MAX_PER_TERM: "8"
          EMAIL_SUBJECT: "📨 Postdoctoral & Research Funding — últimos 14 dias (NL/DE/EU)"
        run: |
          python monitor_editais_exterior.py

