name: Editais Brasil (Nacional + FAPEMA)

on:
  schedule:
    - cron: "20 11 * * *"   # ajuste o horário que preferir (UTC)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt

      # Manual = janela curtinha só pra testar
      - name: Smoke-test (manual)
        if: github.event_name == 'workflow_dispatch'
        env:
          DAYS_BR: 3
          MAX_PER_TERM_BR: 6
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASS: ${{ secrets.GMAIL_APP_PASS }}
          EMAIL_TO_BRASIL: ${{ secrets.EMAIL_TO_BRASIL }}
        run: python monitor_editais_brasil.py

      # Agendado = 14 dias
      - name: Run scheduled
        if: github.event_name != 'workflow_dispatch'
        env:
          DAYS_BR: 14
          MAX_PER_TERM_BR: 12
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASS: ${{ secrets.GMAIL_APP_PASS }}
          EMAIL_TO_BRASIL: ${{ secrets.EMAIL_TO_BRASIL }}
        run: python monitor_editais_brasil.py


