name: Editais Brasil

on:
  schedule:
    - cron: '0 11 * * 4'   # toda quinta 11:00 UTC ≈ 08:00 Fortaleza (UTC-3)
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      # === Segredos obrigatórios ===
      GMAIL_USER: ${{ secrets.GMAIL_USER }}
      GMAIL_APP_PASS: ${{ secrets.GMAIL_APP_PASS }}
      EMAIL_TO_BRASIL: ${{ secrets.EMAIL_TO_BRASIL }}

      # === Parâmetros do monitor ===
      DIAS_JANELA: "14"                # últimos 14 dias
      BRASIL_NACIONAL: "1"            # CAPES/CNPq etc
      BRASIL_ESTADUAL: "FAPEMA"       # limitar estadual apenas ao Maranhão (FAPEMA)

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      # ====== DEBUG OPCIONAL (mostra arquivos e libs) ======
      - name: Debug—where am I?
        run: |
          pwd
          ls -la
          echo "Python:"
          python -V
          echo "Top pip:"
          pip list | sed -n '1,120p'

      - name: Show sources file (Brasil)
        run: |
          echo "=== sources_editais_brasil.yaml ==="
          sed -n '1,200p' sources_editais_brasil.yaml

      # ====== EXECUÇÃO ======
      - name: Run monitor (Brasil)
        run: |
          python monitor_editais_brasil.py

      # ====== Artefato opcional p/ auditoria ======
      - name: Upload artifact (logs/result)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: brasil-output
          path: |
            *.csv
            *.log
            monitor_*.txt
            result_*.json
            !venv/
          if-no-files-found: ignore
